-- Device Registration System Tables

-- Devices table (stores all registered devices)
CREATE TABLE IF NOT EXISTS devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id TEXT UNIQUE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    device_name TEXT DEFAULT 'Lumy Display',
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_online BOOLEAN DEFAULT FALSE,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Registration codes table (temporary codes for pairing)
CREATE TABLE IF NOT EXISTS registration_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    device_id TEXT NOT NULL,
    claimed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    claimed_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);
CREATE INDEX IF NOT EXISTS idx_devices_device_id ON devices(device_id);
CREATE INDEX IF NOT EXISTS idx_registration_codes_code ON registration_codes(code);
CREATE INDEX IF NOT EXISTS idx_registration_codes_device_id ON registration_codes(device_id);
CREATE INDEX IF NOT EXISTS idx_registration_codes_expires_at ON registration_codes(expires_at);

-- Function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to auto-update updated_at on devices table
DROP TRIGGER IF EXISTS update_devices_updated_at ON devices;
CREATE TRIGGER update_devices_updated_at
    BEFORE UPDATE ON devices
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Function to clean up expired registration codes
CREATE OR REPLACE FUNCTION cleanup_expired_codes()
RETURNS void AS $$
BEGIN
    DELETE FROM registration_codes
    WHERE expires_at < NOW();
END;
$$ language 'plpgsql';

-- Row Level Security (RLS) policies

-- Enable RLS on both tables
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE registration_codes ENABLE ROW LEVEL SECURITY;

-- Devices policies: Users can only see their own devices
CREATE POLICY "Users can view their own devices"
    ON devices FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own devices"
    ON devices FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own devices"
    ON devices FOR DELETE
    USING (auth.uid() = user_id);

-- Registration codes policies: Users can view and claim codes
CREATE POLICY "Anyone can view unclaimed codes"
    ON registration_codes FOR SELECT
    USING (claimed_at IS NULL OR claimed_by = auth.uid());

CREATE POLICY "Users can claim codes"
    ON registration_codes FOR UPDATE
    USING (claimed_at IS NULL OR claimed_by = auth.uid());

-- Grant access to authenticated users
GRANT ALL ON devices TO authenticated;
GRANT ALL ON registration_codes TO authenticated;

-- Service role can do anything (for API endpoints)
GRANT ALL ON devices TO service_role;
GRANT ALL ON registration_codes TO service_role;

-- Comments for documentation
COMMENT ON TABLE devices IS 'Registered Lumy devices linked to user accounts';
COMMENT ON TABLE registration_codes IS 'Temporary registration codes for device pairing';
COMMENT ON COLUMN devices.device_id IS 'Unique identifier generated by the device itself';
COMMENT ON COLUMN devices.user_id IS 'Owner of the device';
COMMENT ON COLUMN registration_codes.code IS '6-character code displayed on device (e.g., ABC-123)';
COMMENT ON COLUMN registration_codes.expires_at IS 'Registration codes expire after 1 hour';
